// Här sparar jag alla DOM-element som jag behöver använda
export const dom = {
  openGenerator: document.getElementById("openGenerator"),
  openMyLists: document.getElementById("openMyLists"),
  generatorSection: document.getElementById("generator"),
  myListsSection: document.getElementById("myLists"),
  generatorForm: document.getElementById("generatorForm"),
  searchInput: document.getElementById("searchInput"),
  searchButton: document.getElementById("searchButton"),
  searchStatus: document.getElementById("searchStatus"),
  searchResults: document.getElementById("searchResults"),
  selectedTrackId: document.getElementById("selectedTrackId"),
  selectedTrackBox: document.getElementById("selectedTrack"),
  playlistTitle: document.getElementById("playlistTitle"),
  playlistMeta: document.getElementById("playlistMeta"),
  playlistItems: document.getElementById("playlistItems"),
  saveList: document.getElementById("saveList"),
  connectSpotify: document.getElementById("connectSpotify"),
  myListsContent: document.getElementById("myListsContent"),
  authButton: document.getElementById("authButton"),
  authModal: document.getElementById("authModal"),
  closeAuthModal: document.getElementById("closeAuthModal"),
  authForm: document.getElementById("authForm"),
  authEmail: document.getElementById("authEmail"),
  authPassword: document.getElementById("authPassword"),
  authSubmit: document.getElementById("authSubmit"),
  toggleAuthMode: document.getElementById("toggleAuthMode"),
  authModalTitle: document.getElementById("authModalTitle"),
  authError: document.getElementById("authError"),
  dailyTrackTitle: document.getElementById("dailyTrackTitle"),
  dailyTrackArtist: document.getElementById("dailyTrackArtist"),
  dailyTrackGenre: document.getElementById("dailyTrackGenre"),
  dailyTrackMood: document.getElementById("dailyTrackMood"),
  dailyTrackBpm: document.getElementById("dailyTrackBpm"),
  dailyTrackNote: document.getElementById("dailyTrackNote"),
};

